#/bin/sh
TEMP_FILE=$(mktemp)
tail -c <TOTAL_SIZE> $0 > ${TEMP_FILE}

TEMP_SCRIPT_FILE=$(mktemp)
head -c <SCRIPT_SIZE> ${TEMP_FILE} > ${TEMP_SCRIPT_FILE}

TEMP_INTERPRETER_FILE=$(mktemp)
tail -c <INTERPRETER_SIZE> ${TEMP_FILE} > ${TEMP_INTERPRETER_FILE}

rm ${TEMP_FILE}

chmod +x ${TEMP_INTERPRETER_FILE}

${TEMP_INTERPRETER_FILE} ${TEMP_SCRIPT_FILE}

rm ${TEMP_INTERPRETER_FILE}
rm ${TEMP_SCRIPT_FILE}

exit 0
